#!/usr/bin/env python

import os
import parti.wm
# This means, if an exception propagates to the gtk mainloop, then pass it on
# outwards.
os.environ["PYGTK_FATAL_EXCEPTIONS"] = "1"
try:
    parti.wm.Wm().mainloop()
except:
    import sys, pdb
    #pdb.post_mortem(sys.exc_traceback)
    raise
