#!/bin/sh

. do-build

#/usr/bin/nosetests -w install/lib/python/parti "$@"
#py.test install/lib/python "$@"
#RUNNER="valgrind python"
#RUNNER="gdb --args python"
#RUNNER="pydb --trace"
RUNNER=python
$RUNNER "-Wignore:could not open display" ./yatest.py install/lib/python/parti "$@"