#!/bin/sh

RUNNER=python
#RUNNER="pydb --trace"
#RUNNER="pydb --fntrace"
#RUNNER="gdb python --args"

set -e
rm -rf build install
python make-constants-pxi.py parti/parti._lowlevel.const.txt parti/parti._lowlevel.const.pxi
CFLAGS=-O0 python setup.py install --home=install
# NB Xephyr has a segfault bug in its reset logic -- shouldn't come up
# when run via xinit like this, but use -noreset anyway.
PYTHONPATH=install/lib/python:$PYTHONPATH xinit /bin/sh -c "$RUNNER install/bin/partiwm -sync & x-terminal-emulator" -- /usr/bin/Xephyr :7 -ac -noreset
